version: '3'

services:
    postgres:
        image: postgres
        container_name: nest_database
        restart: always
        tty: true
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - ${POSTGRES_PORT}:${POSTGRES_PORT}
        volumes:
            - .:/var/lib/postgresql/data
